name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install global dependencies
        run: pip install -r .github/workflows/requirements.txt
      - name: Install Dependencies
        run: pip install -r requirements-dev.txt
      - name: Test
        run: pytest tests
